### ISSUE TITLE
Real numbers that are not odd are not even

### ISSUE THREAD

**Issue by thomasdenney** [jonschlinkert/is-even#2]
[The even numbers are defined as the subset of integers that are multiples of 2.][definition]

JavaScript's number type represents values in a subset of real numbers, not a subset of the integers. This library therefore incorrectly defines the set of evens as

```
R \ { x in Z | x % 2 = 1 }
```

where `R` is the set of real numbers, `Z` is the integers, and `\` is the set minus operator. As an example:

```javascript
isEven(0.5) // true, should be false
isEven(1.5) // false
```

[definition]: https://en.wikipedia.org/wiki/Parity_(mathematics)

**Comment by jonschlinkert** [comment]
You're right, `0.5` should be false.  I believe the problem (as the code is written currently) is in how javascript does rounding. `0.5` is not always rounded to `1`, and `0` is even. I suppose we should check for non-integers. Thoughts? Would you like to do a pr to [is-odd](https://github.com/jonschlinkert/is-odd)?

thanks for the issue

**Comment by thomasdenney** [comment]
For real numbers that are not integers the answer should always be false, so modifying is-odd alone is not sufficient; both functions need to assert that their arguments are integral.

**Comment by jonschlinkert** [comment]
> modifying is-odd alone is not sufficient;

Good point, but it should be fixed there first. 

> For real numbers

`is-integer` would fail on a number of use cases handled by `is-number`. We only need to add `Math.(floor|ceil|round).(val) = val`.
