### ISSUE TITLE
Why the heck does this exist?

### ISSUE THREAD

**Issue by wbhob** [jonschlinkert/is-even#3]
I could replicate this functionality with one line:

```
if (parseInt(number) % 2 == 0) {}
```

It checks if the value is a number and if it is divisible evenly by two... What's the big deal?

**Comment by jonschlinkert** [comment]
Well, it depends on how you're using it. For example, let's say we wanted to get the even numbers from this list: 

![image](https://cloud.githubusercontent.com/assets/383994/26272222/5250ddc8-3ce1-11e7-90e1-75a9ce093e5e.png)

Your formula would list me as `even` but you as `undefined`.

**Comment by GNOME-IS-LIFE** [comment]
this is so stupid on so many levels... I just can't.
